import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home = ({ buildTimestamp }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>SoundBendor Lab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>
        Hello!
        This App was built at: {buildTimestamp}
      </p>
      <footer>
      <p> this is the footer !</p>
      </footer>
    </div>
  )
}

export const getStaticProps = () => {
  return {
    props: {
      buildTimestamp: Date.now()
    }
  }
}

export default Home;